apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev
namePrefix: dev-
# nameSuffix: "-001"

images:
  - name: denizyoutube/nginx
    newTag: v1.1.8

